# Generated by Django 4.2.7 on 2023-11-22 00:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Rut')),
                ('nombre_cliente', models.CharField(max_length=30, verbose_name='Nombre ')),
                ('apePaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apeMaterno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('fono', models.IntegerField(unique=True, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nomUsuario', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nombre De Usuario')),
                ('rut_colaborador', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Rut Colaborador')),
                ('nombre_completo', models.CharField(max_length=50, unique=True, verbose_name='Nombre Completo')),
                ('fono', models.IntegerField(unique=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('tipo_perfil', models.IntegerField(choices=[[0, 'Administrador'], [1, 'Vendedor'], [2, 'Mecanico']], verbose_name='Tipo De Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='Nº Producto')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='Nombre Del Producto')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripción')),
                ('precio_unitario', models.IntegerField(verbose_name='Precio Unitario')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('categoria', models.IntegerField(choices=[[0, 'Indumentaria'], [1, 'Accesorio'], [2, 'Repuestos']], verbose_name='Categoría')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now, verbose_name=' Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nombre_proveedor', models.CharField(max_length=30, unique=True, verbose_name='Nombre del Proveedor')),
                ('rut_proveedor', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Rut Proveedor')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('fono', models.IntegerField(unique=True, verbose_name='Teléfono')),
                ('categoria', models.IntegerField(choices=[[0, 'Indumentaria'], [1, 'Accesorio'], [2, 'Repuestos']], verbose_name='Categoría')),
                ('pagina_web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False, verbose_name='Nº en Taller')),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Término')),
                ('tipo_arreglo', models.IntegerField(choices=[[0, 'Ajustes básicos'], [1, 'Cambio de neumáticos'], [2, 'Cambio Frenos'], [3, 'Reparación de Cadena, Pedales y Bielas'], [4, 'Ajuste de Suspensión']], verbose_name='Tipo De Arreglo')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.IntegerField(choices=[[0, 'En proceso'], [1, 'Términado'], [2, 'Atrasado']], verbose_name='Estado')),
                ('modelo_bicicleta', models.CharField(max_length=30, verbose_name='Modelo De Bicicleta')),
                ('estado_pago', models.IntegerField(blank=True, choices=[[0, 'Pendiente'], [1, 'Pagado']], null=True, verbose_name='Estado de Pago')),
                ('abono', models.IntegerField(verbose_name='Abono')),
                ('cliente_rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='Nº Venta')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descipción')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('tipopago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], max_length=30, verbose_name='Tipo De Pago')),
                ('tipo_servicio', models.CharField(choices=[('PRODUCTOS', 'PRODUCTOS'), ('TALLER', 'TALLER')], max_length=30, verbose_name='Tipo De Servicio')),
                ('producto_id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
                ('taller_id_taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.taller')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor'),
        ),
    ]
