# Generated by Django 3.1.2 on 2023-10-26 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Rut')),
                ('nombre_cliente', models.CharField(max_length=30, verbose_name='Nombre ')),
                ('apePaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apeMaterno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('fono', models.IntegerField(unique=True, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nomUsuario', models.CharField(max_length=20, unique=True)),
                ('rut_colaborador', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_completo', models.CharField(max_length=50, unique=True)),
                ('fono', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_perfil', models.IntegerField(choices=[[0, 'Administrador'], [1, 'Vendedor'], [2, 'Mecanico']])),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=80)),
                ('precio_unitario', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('categoria', models.IntegerField(choices=[[0, 'Indumentaria'], [1, 'Accesorio'], [2, 'Repuestos']])),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30, unique=True)),
                ('rut_proveedor', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fono', models.IntegerField(unique=True)),
                ('categoria', models.IntegerField(choices=[[0, 'Indumentaria'], [1, 'Accesorio'], [2, 'Repuestos']])),
                ('pagina_web', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now)),
                ('fecha_termino', models.DateField(default=datetime.datetime.now)),
                ('nombre_trabajo', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[[0, 'Listo'], [1, 'Pendiente'], [2, 'Atrasado'], [3, 'En proceso']])),
                ('modelo_bicicleta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('descripcion', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('tipopago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(choices=[('PRODUCTO', 'PRODUCTO'), ('TALLER', 'TALLER'), ('AMBOS', 'AMBOS')], max_length=30)),
                ('cliente_rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('persona_rut_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.persona')),
                ('producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
                ('taller_id_taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.taller')),
                ('venta_id_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
                ('proveedor_id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor')),
            ],
        ),
    ]
