# Generated by Django 3.1.2 on 2023-10-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='contrasenna',
        ),
    ]
