# Generated by Django 3.1.2 on 2023-10-27 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_factura',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad De Productos'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='precio',
            field=models.IntegerField(verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='total',
            field=models.IntegerField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='id_detalle',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Nº Detalle'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='tipo_servicio',
            field=models.CharField(choices=[('PRODUCTO', 'PRODUCTO'), ('TALLER', 'TALLER'), ('AMBOS', 'AMBOS')], max_length=30, verbose_name='Tipo De Servicio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fono',
            field=models.IntegerField(unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nomUsuario',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre De Usuario'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_completo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut_colaborador',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Rut Colaborador'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_perfil',
            field=models.IntegerField(choices=[[0, 'Administrador'], [1, 'Vendedor'], [2, 'Mecanico']], verbose_name='Tipo De Perfil'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Indumentaria'], [1, 'Accesorio'], [2, 'Repuestos']], verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=80, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Nº Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=30, verbose_name='Nombre Del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.IntegerField(verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Indumentaria'], [1, 'Accesorio'], [2, 'Repuestos']], verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fono',
            field=models.IntegerField(unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Nº Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pagina_web',
            field=models.URLField(blank=True, verbose_name='Página Web'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_proveedor',
            field=models.IntegerField(unique=True, verbose_name='Rut Proveedor'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Listo'], [1, 'Pendiente'], [2, 'Atrasado'], [3, 'En proceso']], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime.now, verbose_name=' Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha_termino',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Término'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='id_taller',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Nº en Taller'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='modelo_bicicleta',
            field=models.CharField(max_length=30, verbose_name='Modelo De Bicicleta'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre_trabajo',
            field=models.CharField(max_length=50, verbose_name='Nombre Del Trabajo'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='valor',
            field=models.IntegerField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descipción'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Nº Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipopago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], max_length=30, verbose_name='Tipo De Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(verbose_name='Total'),
        ),
    ]
