# Generated by Django 4.2.7 on 2023-11-17 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='app.proveedor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_det_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='Nº Venta')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.taller')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
            ],
        ),
    ]
