# Generated by Django 4.2.7 on 2023-11-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_servicio',
        ),
    ]
