# Generated by Django 4.2.7 on 2023-11-17 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_proveedor_detalleventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle_Factura',
        ),
    ]
