# Generated by Django 4.2.7 on 2023-11-17 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_detalle_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime.now, verbose_name=' Fecha de Registro'),
        ),
    ]
