# Generated by Django 4.2.7 on 2023-11-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producto_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='abono',
            field=models.IntegerField(default='0', verbose_name='Abono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='tipo_arreglo',
            field=models.IntegerField(choices=[[0, 'Ajustes básicos'], [1, 'Cambio de neumáticos'], [2, 'Cambio Frenos'], [3, 'Reparación de Cadena, Pedales y Bielas'], [4, 'Ajuste de Suspensión']], verbose_name='Tipo De Arreglo'),
        ),
    ]
