# Generated by Django 4.2.7 on 2023-12-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_taller_cliente_rut_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad_productos_vendidos',
        ),
    ]
