# Generated by Django 4.2.7 on 2023-11-18 05:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_taller_abono_alter_taller_tipo_arreglo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio'),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
