# Generated by Django 4.2.7 on 2023-11-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_taller_cliente_alter_taller_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='cliente',
        ),
        migrations.AddField(
            model_name='taller',
            name='cliente_rut_cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='app.cliente'),
            preserve_default=False,
        ),
    ]
