# Generated by Django 4.2.7 on 2023-12-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_venta_cantidad_productos_vendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad_productos_vendidos',
            field=models.IntegerField(default=0, verbose_name='cantidad de Productos'),
        ),
    ]
