<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-12-14 02:23
=======
# Generated by Django 4.2.7 on 2023-12-14 05:18
>>>>>>> 61d02d355f05572afe5594abf8424d40d2bc0330

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_venta_cantidad_productos_vendidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
    ]
