# Generated by Django 4.2.7 on 2023-11-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_taller_cliente_taller_cliente_rut_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente_rut_cliente',
        ),
    ]
